---
title: "Untitled"
output: html_document
---

```{r}
library(tsibble)
library(tsibbledata)
library(dplyr)
```

```{r}
tsibbledata::gafa_stock
```

```{r}
tdf <- tsibble::tsibble(
  date = 2011:2020,
  letter = LETTERS[1:10],
  value = 1:10,
  key = letter,
  index = date,
)
tdf
```

```{r}
tsibbledata::vic_elec
```

```{r}
elect_filter <- tsibbledata::vic_elec %>%
  dplyr::filter(Time >= as.Date("2012-12-02"))
```

```{r}
elec <- tsibbledata::vic_elec %>%
  dplyr::mutate(quarter = tsibble::yearquarter(Date)) %>%
  tsibble::update_tsibble(
    index = quarter,
    key = Time
  )
```

```{r}
elec %>%
  tsibble::index_by(quarter) %>%
  dplyr::summarise(avg_demand = mean(Demand))
```

1. recreate the olympic_running tsibble

```{r}
tsibbledata::olympic_running
```

```{r}
oly <- tibble::tibble(tsibbledata::olympic_running)
```

```{r}
oly2 <- tsibble::as_tsibble(oly, key = c(Length, Sex), index = Year)
```


2. What is the average time by each year
```{r}
oly2 %>%
  dplyr::group_by(Length) %>%
  tsibble::index_by(Year) %>%
  dplyr::summarize(avg = mean(Time, na.rm = TRUE))
```

