---
title: "Untitled"
output: html_document
---

```{r}
library(tsibbledata)
library(tsibble)
library(feasts)
library(fable)
```

```{r}
vic_elec %>% fabletools::autoplot(Demand)
```

```{r}
vic_elec %>% fabletools::autoplot(log(Demand))
```

$$
w_t = 
\begin{cases}
    log(y_t), & \text{if } \lambda = 0; \\
    (y_t^\lambda - 1)/\lambda, & \text{otherwise}.
\end{cases}
$$

```{r}
library(readr)
library(ggplot2)
```

```{r}
elec <- readr::read_csv(here::here("data", "electricity_france.csv"))
```


```{r}
elec <- elec %>% 
    as_tsibble(index=Date) %>% 
    dplyr::filter(Date >= as.Date('2007-01-01'))

lambdas <- c(0, seq(from=0.1, to=2, by=0.05))
trans_elec <- lambdas %>% 
    purrr::map_df(
        ~ elec %>% dplyr::select(Date, ActivePower) %>% 
            dplyr::mutate(
                ActivePower=box_cox(ActivePower, .x), 
                Lambda=.x) %>% 
            as_tibble()
    ) %>% 
    dplyr::mutate(Power=as.character(Lambda))

```

```{r}
lambda <- elec %>% 
   fabletools::features(ActivePower, features=feasts::guerrero) %>% 
   dplyr::pull(lambda_guerrero)

lambda
```



























